move spelling check into one step

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -46,18 +46,17 @@ jobs:
     - name: Check spelling
       id: spellcheck
       run: |
-        git ls-files | xargs uvx codespell
-      continue-on-error: true
-
-    - name: Handle Spelling Results
-      run: |
+        SPELLING_RESULTS = git ls-files | xargs uvx codespell
+        echo $SPELLING_RESULTS
+        
         echo "### Spelling check" >> $GITHUB_STEP_SUMMARY
-        if [[ "${{ steps.spellcheck.outcome }}" == "failure" ]]; then
+        if [$? == 0]; then
           echo '> [!WARNING]' >> $GITHUB_STEP_SUMMARY
-          git ls-files | xargs uvx codespell | xargs -L 1  echo '>'  >> $GITHUB_STEP_SUMMARY
+          $SPELLING_RESULTS | tr '\n' '\000' | xargs -0 echo '>' >> $GITHUB_STEP_SUMMARY
         else
-          echo "Sucess! <br>" >> $GITHUB_STEP_SUMMARY
+           echo "No errors found! <br>" >> $GITHUB_STEP_SUMMARY
         fi
+      continue-on-error: true
 
     # Run tests
     - name: Run tests
